version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      event-app:
        aliases:
          - mongodb.eventapp.com
  maven:
    build:
      context: ./
      dockerfile: Dockerfile-build
    image: build-app
    volumes:
      - ./:/usr/src/eventapp/
    networks:
      - event-app
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: event-app
    volumes:
      - ./:/usr/src/eventapp/
    entrypoint: /usr/src/eventapp/entrypoint.sh
    environment:
      - MONGODB_URI=mongodb://mongodb.eventapp.com/eventDB
    ports:
      - 8080:8080
    networks:
      - event-app
    depends_on:
      - mongo
networks:
  event-app:
    driver: bridge
